#!/bin/bash
# remove-old - removes old versions from your tor mirror
# by Sahal Ansari github.com/sahal
#
# ./remove-old genignore|noaccess|duh|delete
# see below case statement for more information

# import some variables
source defaults.cfg

# todo: explain these arguments to the user...
if [ -z $1 ]; then
	echo "Please run this script with an argument, e.g.:"
	echo "./remove-old genignore|noaccess|duh|delete"
	exit 1
fi

# FUNCTION: bash array diff example from http://bit.ly/Lm9bS2
diff(){
  awk 'BEGIN{RS=ORS=" "}
       {NR==FNR?a[$0]++:a[$0]--}
       END{for(k in a)if(a[k])print k}' <(echo -n "${!1}") <(echo -n "${!2}")
}

cd "$dldir"

# put list of files in $dldir into array a
a=( $(find . -name "*.asc" -o -name "*.gz" -o -name "*.xz" -o -name "*.asc" -o -name "*.dmg" -o -name "*.exe" | sed -e s@\./@@ -e s@.*/@@ | sort | uniq ))

# these are the only files that should be there (current mirror)
b=( $( cat "$tmpdir"/torbrowser-wantedlocales "$tmpdir"/tor-source | sort | uniq ) )

# files that need to be removed
c=($(diff a[@] b[@]))

# test array
for var in "${c[@]}"
do
	# this adds the full path name to the filename :)
	fullpath=$(find "$dldir" -name "${var}" -print)

	case $1 in 

	genignore) # generate IndexIgnore to use with apache .htaccess file
		echo "$fullpath"
		echo -ne "IndexIgnore " &&  echo "$fullpath"
		;; 

	noaccess) # remove access to the files for others and groups
		echo "$fullpath"
		chmod og= "$fullpath"
		;;

	duh) # see the file name and sizes of all the files
		echo "$fullpath"
		du -h "$fullpath"
		;;

	delete) # delete the files
		echo "$fullpath"
		rm "$fullpath"
		;;

	*)
		# just print the damn names!
		echo "$fullpath"
	esac
done
